name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering Render deployment..."
          response=$(curl -s -w "%{http_code}" -o /tmp/render_response.txt -X POST https://api.render.com/deploy/srv-cul7vh3qf0us73bvukp0?key=$RENDER_API_KEY)
          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with status code $response"
            cat /tmp/render_response.txt
            exit 1
          else
            echo "Deployment successful!"
          fi
